# Generated by Django 4.1.7 on 2023-04-02 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribe',
            field=models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
