# Generated by Django 4.1.7 on 2023-04-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0004_categorysubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorySubscriber',
        ),
    ]
