# Generated by Django 4.1.7 on 2023-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0005_delete_categorysubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_category_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_category_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
