# Generated by Django 4.1.7 on 2023-05-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0006_category_name_category_en_category_name_category_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='header_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_rating_en',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_rating_ru',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_post_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_post_ru',
            field=models.TextField(null=True),
        ),
    ]
